### ISSUE TITLE
Checkboxes and radios not showing up in Firefox

### ISSUE THREAD

**Issue by DevElCuy** [KXStudio/KXStudio#9]
This is an annoying bug since elements are actually there but are not visible on white background (most of websites). After a while I managed to fix it adding a css rule:

``` CSS
.check, .radio {
  border-style: solid;
} 
```

The file is located at: /usr/share/themes/KXStudio/gtk-3.0/gtk-widgets.css yet I can't find it in your git repo.
